"""add file

Revision ID: b8e7c984aad9
Revises: fe03dea0363a
Create Date: 2023-04-14 20:26:17.940979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8e7c984aad9'
down_revision = 'fe03dea0363a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('file', sa.String(length=5000), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'file')
    # ### end Alembic commands ###
